#!/usr/bin/env python3
"""Run security scans on all Qontinui Python repositories."""

from pathlib import Path

from qontinui_devtools.security import SecurityAnalyzer

REPOS = [
    ("qontinui", "D:/qontinui_parent_directory/qontinui"),
    ("qontinui-api", "D:/qontinui_parent_directory/qontinui-api"),
    (
        "qontinui-web/backend",
        "D:/qontinui_parent_directory/qontinui-web/backend",
    ),
    ("qontinui-mcp", "D:/qontinui_parent_directory/qontinui-mcp"),
    ("qontinui-devtools", "D:/qontinui_parent_directory/qontinui-devtools"),
    ("qontinui-train", "D:/qontinui_parent_directory/qontinui-train"),
    ("qontinui-finetune", "D:/qontinui_parent_directory/qontinui-finetune"),
]


def main():
    results = {}

    for repo_name, repo_path in REPOS:
        repo_path_obj = Path(repo_path)
        if not repo_path_obj.exists():
            print(f"Skipping {repo_name} (not found)")
            continue

        print(f"\n{'='*60}")
        print(f"Scanning: {repo_name}")
        print(f"{'='*60}")

        analyzer = SecurityAnalyzer()
        report = analyzer.analyze_directory(str(repo_path_obj))

        results[repo_name] = report

        print(f"Files scanned: {report.total_files_scanned}")
        print(f"Total vulnerabilities: {len(report.vulnerabilities)}")
        print(f"Scan duration: {report.scan_duration:.2f}s")
        print()
        print("By severity:")
        print(f"  CRITICAL: {report.critical_count}")
        print(f"  HIGH: {report.high_count}")
        print(f"  MEDIUM: {report.medium_count}")
        print(f"  LOW: {report.low_count}")
        print(f"  INFO: {report.info_count}")

        if len(report.vulnerabilities) > 0:
            print()
            print("First 10 vulnerabilities:")
            for i, vuln in enumerate(report.vulnerabilities[:10], 1):
                print(f"\n{i}. {vuln.severity.value}: {vuln.type.value}")
                print(f"   File: {Path(vuln.file_path).name}:{vuln.line_number}")
                print(f"   {vuln.description[:100]}...")

    # Write summary report
    summary_path = Path("D:/qontinui_parent_directory/.dev-logs/improve-all-security-audit.md")
    summary_path.parent.mkdir(exist_ok=True)

    with open(summary_path, "w", encoding="utf-8") as f:
        f.write("# Security Audit Summary\n\n")
        f.write("Generated by qontinui-devtools SecurityAnalyzer\n\n")

        f.write("## Overview\n\n")
        f.write("| Repository | Files | Total | Critical | High | Medium | Low | Info |\n")
        f.write("|------------|-------|-------|----------|------|--------|-----|------|\n")

        for repo, report in results.items():
            f.write(f"| {repo} | {report.total_files_scanned} | {len(report.vulnerabilities)} | ")
            f.write(f"{report.critical_count} | {report.high_count} | {report.medium_count} | ")
            f.write(f"{report.low_count} | {report.info_count} |\n")

        f.write("\n## Critical and High Severity Findings\n\n")

        for repo, report in results.items():
            critical_high = [
                v for v in report.vulnerabilities if v.severity.value in ["CRITICAL", "HIGH"]
            ]

            if critical_high:
                f.write(f"\n### {repo}\n\n")
                for vuln in critical_high:
                    f.write(f"**{vuln.severity.value}**: {vuln.type.value}\n")
                    f.write(f"- File: `{vuln.file_path}:{vuln.line_number}`\n")
                    f.write(f"- Description: {vuln.description}\n")
                    f.write(f"- Remediation: {vuln.remediation}\n")
                    f.write(f"- CWE: {vuln.cwe_id}, OWASP: {vuln.owasp_category}\n\n")

        f.write("\n## Detailed Findings by Repository\n\n")

        for repo, report in results.items():
            if len(report.vulnerabilities) > 0:
                f.write(f"\n### {repo}\n\n")
                f.write(f"Total: {len(report.vulnerabilities)} vulnerabilities\n\n")

                # Group by type
                by_type = {}
                for vuln in report.vulnerabilities:
                    vtype = vuln.type.value
                    if vtype not in by_type:
                        by_type[vtype] = []
                    by_type[vtype].append(vuln)

                for vtype, vulns in sorted(by_type.items()):
                    f.write(f"\n#### {vtype} ({len(vulns)})\n\n")
                    for vuln in vulns[:5]:  # Show first 5 of each type
                        f.write(
                            f"- **{vuln.severity.value}**: {vuln.file_path}:{vuln.line_number}\n"
                        )
                        f.write(f"  {vuln.description}\n")

    print(f"\n{'='*60}")
    print(f"Summary written to: {summary_path}")
    print(f"{'='*60}")


if __name__ == "__main__":
    main()
